### PR TITLE
Porting TSCH to iotlab-m3

### PR DESCRIPTION
**Pull request by simonduq**
Implements missing radio features on the M3 required for running TSCH. Tested on two nodes on a table, not in IoT-Lab. The patch is far from perfect, there are a few modifications in the driver that I'm not happy with, comments are welcome.

A few modifs are also required in openlab, see https://github.com/iot-lab/openlab/pull/5

### CODE REVIEW

**Comment by cladmi** [comment]
I would prefer to split in different commits between what are general improvements, and what is required for TSCH.

`ifndefs` for all netstack conf and the functions for setting channel are simply better code and deserve their own commit.

Regarding the change of payload size from 125 to 127, did you had issues with this value ?
In fact there is only 125 usable payload.
And was there something wrong with PACKETBUF_CONF_SIZE, it may not be the right way of setting it, and so it also deserve its own commit.

The RADIO_DELAY_* macro are unused for the moment. And I wonder if it wouldn't be better to have them as RADIO_DELAY_US_* and do the conversion to TICKS somewhere else. There is some kind on inverted dependency in this way.

Now to understand a bit more:
Adding support for TSCH is mainly adding support for 'poll mode' and setting channel right ?
And using `rf2xx_get_status` is because some interrupts are disabled.

**Comment by simonduq** [comment]
Right, I'll definitely rebase and split this in several commits.
The `RADIO_DELAY_` macros are used by TSCH (see `core/net/mac`). TSCH expects a time in ticks. Having it in usec would be a good idea, I agree, but that would rather be a PR to Contiki upstream ;)

As for the payload size I'm unsure, because 802.15.4 mandates the support of 127-Byte frames, the RF2xx claims to be compilent also the datasheet mentions 127-Byte frames at many different places such as:
```
The maximum value of frame_length is 127 bytes. That means that n ≤ 130 for Frame Buffer
read and n ≤ 129 for Frame Buffer write accesses.
```

Regarding what it takes to port TSCH, yes, but also a little more than you mention. The list of required features is here:
https://github.com/contiki-os/contiki/blob/master/core/net/mac/tsch/README.md#porting-tsch-to-a-new-platform

Thanks

**Comment by cladmi** [comment]
I was looking in release-3.0 branch so didn't found the macros… It's better with master.
So ok that's fine this way.

It's 127 bytes frames, however auto CRC is enabled and added by the hardware.
Which means the last 2 bytes get replaces by the CRC: http://www.atmel.com/images/doc8111.pdf
Section 8.2.3

If needed, the last timestamp precision can be improved by using dig2.
The SFD frame IRQ is hardware timed and can be converted back to an RTIMER time.

Last packet RSSI and LQI is simple to add, I can write it if you want.

**Comment by simonduq** [comment]
Wow indeed, that really is a pity... will need to revert to 125 then.
More precision is useful to TSCH yes we should discuss that.
My personal advice with Contiki: always prefer master over releases :)

**Comment by simonduq** [comment]
Have updated and rebased the PR. The previous code used to break ContikiMAC, this is now fixed. Tested at scale successfully. Ready to merge AFAIK.

**Comment by simonduq** [comment]
I addressed your comments @cladmi (note your comments on the previous commit are not visible anymore, as that particular commit hash is not in this branch history anymore after rebase)

**Comment by cladmi** [comment]
Currently commit adding "RF2XX_SOFT_PREPARE" break contiki-mac example.
I'm trying a simple BR (tunslip6) + http-server node.

https://gist.github.com/cladmi/cb8ef59b7a5feb6491ca

I will investigate on this.

**Comment by cladmi** [comment]
The two while at the end looks problematic, the one added for poll_mode.
It's blocking on the first one, will continue checking.

**Comment by simonduq** [comment]
OK, strange, I thought I tested this version with ContikiMAC (rime examples, both broadcast and unicast).
Have you tried the whole branch or are you incorporating the commits one at a time?

**Comment by cladmi** [comment]
Both, I tried the final version and bisected to find the culprit.

**Comment by simonduq** [comment]
sounds great, thanks

**Comment by cladmi** [comment]
So I have news! It will mainly concern the "poll mode" commit.

Long story short, the only needed stuff in the commit is adding the timestamp and "if(!poll_mode)".
I rebased the branch in: https://github.com/iot-lab/contiki-upstream-unstable/tree/pr/pr/tsch-m3

Also removing the `rf2xx_irq_enable` in hard_prepare does no harm.

The `pr/pr/tsch-m3` branch works for me.

-----

Now long story long

I tried removing the two `while` lines in mentioned before, test passed.
Then applying the next commit adding poll mode. It failed.

After some digging, I saw that when we change the state we are not in critical sections.
Adding a critical section on one change helped, I could see the route but not ping.

And also I found this in the code in the same time.

https://github.com/iot-lab/contiki-upstream-unstable/blob/377518c24be4e2f6b65949f9f11dfae3308f9a6f/platform/openlab/radio-rf2xx.c#L289

So yeah the `rf2xx_read_status` may also conflict with the interrupt in non poll mode.

I added critical sections everywhere that looked necessary but it failed :/


I also noticed that, the interrupt is required for poll mode, so the state is set by the interrupt handler and the new code using "read_status" and modifying the state is not needed anymore and even harmful. I got once the state set to XXX_DONE before the interrupt handler executed.

(While writing the message I also saw: https://github.com/iot-lab/contiki-upstream-unstable/blob/377518c24be4e2f6b65949f9f11dfae3308f9a6f/platform/openlab/radio-rf2xx.c#L757 so read_status in the main code is a bad idea)

**Comment by cladmi** [comment]
Also, sorry for the delay in reviewing the PR.

**Comment by simonduq** [comment]
OK, thanks.
Have you tried with TSCH?
I don't really see how it will work with https://github.com/iot-lab/contiki-upstream-unstable/commit/9a65d6593acc72fbc21d1568564bcaad410a767b, given that transmission in TSCH occur from rtimer ISR (higher priority than radio interrupts)

**Comment by cladmi** [comment]
No only tried contikimac. So yeah I should try TSCH when testing also.

The different priority interrupts change the problem that's true.
So if I understand correctly, when transmitting, the interrupt handler would be called later for nothing.
But on reception it will be called normally that's right?
So it could be disabled for TX in poll mode.

If your loop breaks contikimac It means we will need to add some `if (poll_mode)`.
That's a good thing also because comments saying "it's because higher priority" with tsch can be added.

As the wait is made in the rtimer isr, it means your are blocking in an interrupt handler?
I understand why you wanted "prepare" to actually copy the packet to the fifo in this case.

**Comment by simonduq** [comment]
Reception is also done partly from interrupt in TSCH. The TSCH implementation is very interrupt-intensive, which is something that might be improved in the future. The priority is to get accurate timing. The reason for preparing before sending is mostly to get predictable/consistent delay between a call to .transmit() and the actual start of Tx.

I agree on adding comments on ISR priority, yes!

What puzzles me is that I did get the whole thing to work nicely with ContikiMAC, tried in the testbed. But I guess a last change minute slipped in that broke everything.. I'm almost certain I had ContikiMAC running even with the `read_status`. Will look again into this when I find time.

**Pull request merged**
